### ISSUE TITLE
proxy setup

### ISSUE THREAD

**Issue by jonasman** [marcuswestin/WebViewProxy#4]
Hi guys, any idea how to use this lib to route all my http connections trough an http proxy with password?

**Comment by yinyinliushang** [comment]
If the URL isn't full , like 
 /t?mid=355288&rt=1&oid=65186&im=1&t=1432798631&data=44%2C1156410100%2C136%2C1798615551989237%2C5520%2C22806237%2C10009232%2C11%2C4%2C2%2Cletv%2C%2C1&s=ddb3
how to intercept part URL since 
[WebViewProxy handleRequestsMatching:[NSPredicate predicateWithFormat:@"absoluteString MATCHES[cd] '^http:'"] handler:^(NSURLRequest* req, WVPResponse *res) {
    [res respondWithText:@"Hi!"];
}];
isn't userful
Addition, all URL is intercepted but movie URL  by NSURLSession
How to intercept movie URL?
Best wishes.

**Comment by samheather** [comment]
@jonasman did you figure out how to pass all the data in your app webview through a proxy server? I'm working on an internal project that needs this.

**Comment by jonasman** [comment]
My second comment explains how i did it.

**Comment by samheather** [comment]
@jonasman how did you catch requests from the UIWebView from people pressing links and re-route them all, including embedded images etc, via an NSURLRequest?

**Comment by jonasman** [comment]
Using nsurlptrocol you can redirect all requests that are done in your app. Check docs for that.
